os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Release
platform:
  - Win32
  - x64
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.29.0
    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly

build_script: appveyor.bat
